// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // AGP actualizado a la versión 8.9.1 para soportar androidx.activity:1.11.0 y API 36
        classpath 'com.android.tools.build:gradle:8.9.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    minSdkVersion = 24
    compileSdkVersion = 36
    targetSdkVersion = 36
    androidxAppCompatVersion = '1.6.1'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.12.0'
    androidxCoreKtxVersion = '1.12.0'
    androidxJunitVersion = '1.1.5'
    androidxJUnitVersion = '1.1.5'
    androidxEspressoCoreVersion = '3.5.1'
    junitVersion = '4.13.2'
    coreSplashScreenVersion = '1.0.1'
}